### ISSUE TITLE
PrimInt: total number of bits

### ISSUE THREAD

**Issue by dvdhrm** [rust-num/num-traits#107]
Hi!

Is there any way to get the total number of bits in an `PrimInt`? That is, the compile-time equivalent of:

    p.count_zeros() + p.count_ones()

I am implementing floored/ceiled logarithms on `PrimInt` and these make use of the leading/trailing counters. These need the inverse of the respective functions, so I need to calculate the total bitlength of a number.

I thought about using `std::mem::size_of()`, but that does not sound right, as it includes possible state-tracking data. Or is `PrimInt` meant to allow the use of `sizeof()`?

Thanks!
David

**Comment by cuviper** [comment]
> I thought about using `std::mem::size_of()`, but that does not sound right, as it includes possible state-tracking data.

That would be fine for the actual primitive integers, but I suppose generically you're right that an arbitrary `PrimInt` could have other data.

For generic `T: PrimInt`, I think you could use `T::zero().count_zeros()`. While this isn't exactly a compile-time constant, the optimizer will probably reduce that to a constant anyway.

**Comment by dvdhrm** [comment]
> For generic `T: PrimInt`, I think you could use `T::zero().count_zeros()`. While this isn't exactly a compile-time constant, the optimizer will probably reduce that to a constant anyway.

This is what I ended up doing.

If you want, you can close this and I will comment on #11 that `zero().count_zeros()` is a viable alternative?

Thanks!

**Comment by cuviper** [comment]
OK, closing. I'm not sure how this is an "alternative" to #11 documentation though...

**Comment by dvdhrm** [comment]
Nah, I meant I will comment on #11 that `zero().count_zeros()` is an alternative to `std::mem::size_of()` ;)

**Comment by Timmmm** [comment]
I think this should be reopened. Neither `zero().count_zeros()` nor `std::mem::size_of(x) * 8` are particularly obvious, and it's not obvious that they would be optimised to a constant (though I verified that both are).
