### ISSUE TITLE
+= operator for num_traits::Float

### ISSUE THREAD

**Issue by a-rodin** [rust-num/num-traits#109]
This code doesn't compile
```rust
use num_traits::Float;

fn inc<T: Float>(mut x: T) -> T {
    x += T::one();
    x
}

fn main() {
    inc(5f32);
}
```
with error 
```
binary assignment operation `+=` cannot be applied to type `T`
```
[(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a9892199b5fcd79e43ded38bce1d1c15)

However, changing `x += T::one()` to `x = x + T::one()` works. It seems like `+=` operator could have been implemented for `num_traits::Float`, as it is implemented for built-in float types.

**Comment by cuviper** [comment]
This is because `Float` has been around longer than the *`Assign` traits, and it would be a breaking change to add them to `Float` now. Perhaps in a future semver bump we could. In the meantime, you can require the combined `Float + NumAssign` for this.
