### ISSUE TITLE
Version 0.2.7 breaks nostd builds

### ISSUE THREAD

**Issue by mullr** [rust-num/num-traits#115]
With 0.2.7, we're now getting: 

```
error[E0407]: method `to_u128` is not a member of trait `ToPrimitive`
  --> /home/mullr/.cargo/registry/src/github.com-1ecc6299db9ec823/num-complex-0.2.1/src/cast.rs:7:9
   |
7  | /         fn $to(&self) -> Option<$ty> {
8  | |             if self.im.is_zero() { self.re.$to() } else { None }
9  | |         }
   | |_________^ not a member of trait `ToPrimitive`
...
26 |       impl_to_primitive!(u128, to_u128);
   |       ---------------------------------- in this macro invocation
```
.. and a boatload of other related errors. 

It seems likely that this is related to the autocfg change made in this release.

**Comment by cuviper** [comment]
In theory, `autocfg` should have the exact same code that the manual build script did before, but it's possible I made a mistake in extracting that. Can you share `cargo build -v` output? and `rustc -Vv`?

**Comment by cuviper** [comment]
Ugh, I see it. I tried to be smarter in `autocfg` by probing the given `TARGET`, but this doesn't work for no-std targets since I don't have `#![no_std]` in there.

**Comment by cuviper** [comment]
This should be fixed by `autocfg 0.1.3`.

I will also increase the dependency here to make sure it sticks.

**Comment by cuviper** [comment]
I had to yank that, because it broke CI for rust itself! Not sure why, but I'll investigate more tomorrow...

**Comment by cuviper** [comment]
OK, we should be good again. :crossed_fingers: 
- autocfg 0.1.4
- num-integer 0.1.41
- num-iter 0.1.39
- num-traits 0.2.8
