### ISSUE TITLE
Casting floats to integers does not check overflow

### ISSUE THREAD

**Issue by cuviper** [rust-num/num-traits#12]
_From @photino on October 4, 2015 15:49_

The following code 

``` rust
num::cast::<f64, i32>(1.0e+123f64)
```

will return

``` rust
Some(-2147483648)
```

instead of `None`.

_Copied from original issue: rust-num/num#119_

**Comment by cuviper** [comment]
I think the root problem is `impl_to_primitive_float`, which just typecasts to integers with `as`.

**Comment by cuviper** [comment]
_From @apopiak on November 25, 2015 18:49_

I'd like to try this one.

**Comment by cuviper** [comment]
@apopiak go for it!

**Comment by cuviper** [comment]
Technically this is UB -- rust-lang/rust#10184 -- and I believe rustc is planning to implement saturating float casts.  I think even with that, our conversion traits should prefer `None` instead of saturating.

**Comment by apopiak** [comment]
Yeah, sorry I never got back on that. Consider me no longer working on this until I post otherwise.

**Comment by dbarella** [comment]
I think I have a patch that fixes this!
