### ISSUE TITLE
Replace `transmute()` for float casts with `to_bits()`?

### ISSUE THREAD

**Issue by icefoxen** [rust-num/num-traits#123]
There's a few places where [`transmute()` is used to turn a float into its bit representation](https://github.com/rust-num/num-traits/blob/master/src/float.rs#L769).  Rust 1.20 provides `f32::to_bits()` to do the same job, and it *appears* to be available in `#[no_std]`.  Is there any particular reason not to use it over `transmute()`, since that would remove the only `unsafe` uses from this library?

**Comment by nestordemeure** [comment]
I was precisely about to post an issue because I could not find to_bits and needed it to convert a code from f64 to be generic over Float.

**Comment by cuviper** [comment]
This is about internally using `f32`/`f64::to_bits()` instead of `transmute`. Adding `Float::to_bits()` is a different question, complicated by the fact that the output needs an associated type. Please do file a separate issue if you want this -- I'd probably make it a new trait.

**Comment by cuviper** [comment]
We stopped using `transmute` for this in #240, commit fd601a8d4de1ab4e11c65929c679ae0c14fc7099.
