### ISSUE TITLE
Why does the Float trait require copy and can it be changed to clone?

### ISSUE THREAD

**Issue by josyoun** [rust-num/num-traits#133]
Is there any particular reason why the `Float` trait requires `copy`?  Could it be changed to `clone`?

Part of the reason that I'm asking is that the `Float` trait allows general numerical codes to be written on different floating point types.  While this includes code generic to `f32` and `f64`, it also potentially includes running the same code over an automatic differentiation (AD) type as well as other computational types like those from interval arithmetic.  I believe both AD and interval arithmetic types can implement everything within the `Float` trait except for `copy`.  Or, to be more precise, it's possible to implement a forward mode AD algorithm that implements `copy`, but this is the wrong algorithm for many applications.  The reverse mode algorithm for AD generally needs to build up a tape or a computational tree in order to calculate derivatives and this requires things like `Rc`, which can be cloned, but not copied.

Anyway, there may be a good reason for keeping things as is.  That said, if `Copy` can be changed to `Clone`, then I think a wider variety of algorithms and types could make use of the `Float` trait.

**Comment by cuviper** [comment]
We probably should have had a separate `PrimFloat`, like `PrimInt`, and left `Float` etc. more general as you suggest. However, it would be a breaking change to remove `Copy` now, as users that require `T: Float` are allowed to use its supertraits too. If we ever do a semver-bump of num-traits, there's a lot about the whole `Float*` traits that should be reconsidered like this.

I have no experience with AD, but it sounds very cool!

**Comment by josyoun** [comment]
OK, cool and I think you're right to leave things as is for now.  I've been doing some tinkering with the AD types and there's a bunch of issues that have arisen with things like references that are akin to what's been reported in [issue 94](https://github.com/rust-num/num/issues/94).  As such, I'll suggest closing this issue out until I can gather more information and you're into the mood to version bump.  Basically, let me

- Code some AD algorithms

- Code some generic numerical routines

- Run the routines with both the AD types and things like f64

That should give a better idea of exactly what kind of interface is necessary for this kind of general numeric programming.  At that point, I'll pass by a note and you can make a determination as to whether you want to generalize things and what they may look like.  If something comes up earlier and you or someone else has a good solution for this kind of interface, please let me know and thanks.
