### ISSUE TITLE
no_std is broken

### ISSUE THREAD

**Issue by MarkSwanson** [rust-num/num-traits#138]
My Cargo.toml has:
num-traits = { version = ">=0.2.0", default-features = false }

My crate fails to compile when I build it like this:
cargo --verbose build --target thumbv7m-none-eabi

(What confuses me in the output is this --> --cfg 'feature="default"' --cfg 'feature="std"')
(Why is Cargo ignoring: default-features = false ?)

   Compiling num-traits v0.2.8
     Running `rustc --crate-name num_traits /home/mswanson/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.8/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=616873d37e025f24 -C extra-filename=-616873d37e025f24 --out-dir '/mnt/sdb2/@home/mswanson/src/stm32/rust-compression/target/thumbv7m-none-eabi/debug/deps' --target thumbv7m-none-eabi -L 'dependency=/mnt/sdb2/@home/mswanson/src/stm32/rust-compression/target/thumbv7m-none-eabi/debug/deps' -L 'dependency=/mnt/sdb2/@home/mswanson/src/stm32/rust-compression/target/debug/deps' --cap-lints allow --cfg has_i128`
error[E0463]: can't find crate for `std`
  --> /home/mswanson/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.8/src/lib.rs:21:1

**Comment by CryZe** [comment]
It's probably a dev dependency that is using num-traits as well.

**Comment by cuviper** [comment]
Yes, I think it's an instance of <https://github.com/rust-lang/cargo/issues/2589>. You could use [`cargo tree`](https://crates.io/crates/cargo-tree) to see where crates are used in your dependency tree, especially inverted like `cargo tree -i -p num-traits`.

**Comment by Sympatron** [comment]
This is probably fixed by now. The new resolver should do a better job of resolving things like that and it hasn't come up again for 4 years.
