### ISSUE TITLE
`std::num::Checked{Add,Sub,Mul,Div}` should have type parameters

### ISSUE THREAD

**Issue by cuviper** [rust-num/num-traits#15]
_From @steveklabnik on February 11, 2015 1:35_

<a href="https://github.com/lifthrasiir"><img src="https://avatars.githubusercontent.com/u/323836?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lifthrasiir](https://github.com/lifthrasiir)**
_Monday Apr 14, 2014 at 12:33 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/13510_

_This issue was labelled with: A-libs in the Rust repository_

---

The corresponding `std::ops` traits have both the type of right hand side operand and the type of result, while `Checked*` traits do not (and always assume that both operands and result have the same type). There is no real reason to make `Checked*` traits behave differently from `std::ops` traits, and having them as is hampers advanced uses of operator overloading: for example, if the scalar type (e.g. `DateTime`) and difference type (e.g. `Duration`) are distinct from each other then the current scheme wouldn't work at all.

_Copied from original issue: rust-num/num#59_

**Comment by cuviper** [comment]
_From @clarcharr on September 30, 2017 21:40_

Adding onto this, there should be checked versions of `Rem`, `Shl`, and `Shr` as well.

**Comment by clarcharr** [comment]
IMHO these traits should also take things by value for consistency with the original traits.

**Comment by cuviper** [comment]
I've decided to limit the clutter of `breaking change` issues, so they will now be tracked collectively in #47.  I'm closing this issue for now as `postponed` but we can still discuss its merits here as needed.

**Comment by regexident** [comment]
For sake of completeness it's worth mentioning that not just the `Checked{Add,Sub,Mul,Div}` set of traits should have type parameters, but all of these, too:

- `Wrapping{Add,Sub,Mul,Div}`
- `Saturating{Add,Sub,Mul,Div}`
- `Overflowing{Add,Sub,Mul,Div}`

Same for `Unchecked{Add,Sub,Mul,Div}`, should [they](http://doc.rust-lang.org/1.50.0/std/primitive.i8.html#method.unchecked_add) get added to `num-traits` in the future.

**Comment by regexident** [comment]
To add another motivation for adding type parameters consider vector-scaling arithmetic:

```rust
impl CheckedMul<Scalar> for Vector {
    fn checked_mul(&self, v: &Self) -> Option<Self> {
                           // ~~~~
                           // not possible as we would require `Scalar` here,
                           // not `Self` (problem caused by `Self: Mul<Self, Output = _>`)
                                                                       ~~~~
    }
}
```

```rust
impl CheckedMul<Vector> for Scalar {
    fn checked_mul(&self, v: &Self) -> Option<Self> {
                           // ~~~~            ~~~~
                           // not possible either as we would require `Vector` here,
                           // not `Self` (problem caused by `Self: Mul<Self, Output = Self>`)
                                                                       ~~~~           ~~~~
    }
}
```

**Comment by regexident** [comment]
Since this issue doesn't actually mention what the desired re-definitions would actually look like I'd like to take the opportunity to provide one such recommendation here:

`Checked{Add,Sub,Mul,Div}`:
```rust
pub trait Checked…<Rhs = Self> {
    type Output;

    #[must_use]
    fn checked_…(self, rhs: Rhs) -> Option<Self::Output>;
}
```

`Unchecked{Add,Sub,Mul,Div}`:
```rust
pub trait UncheckedAdd<Rhs = Self> {
    type Output;

    #[must_use]
    fn unchecked_add(self, rhs: Rhs) -> Self::Output;
}
```

`Saturating{Add,Sub,Mul,Div}`:
```rust
pub trait Saturating…<Rhs = Self> {
    type Output;

    #[must_use]
    fn saturating_…(self, rhs: Rhs) -> Self::Output;
}
```

`Wrapping{Add,Sub,Mul,Div}`:
```rust
pub trait Wrapping…<Rhs = Self> {
    type Output;

    #[must_use]
    fn wrapping_…(self, rhs: Rhs) -> Self::Output;
}
```

`Overflowing{Add,Sub,Mul,Div}`:
```rust
pub trait Overflowing…<Rhs = Self> {
    type Output;

    #[must_use]
    fn overflowing_…(self, rhs: Rhs) -> (Self::Output, bool);
}
```
