### ISSUE TITLE
Float trait doesn't require copysign function

### ISSUE THREAD

**Issue by hombit** [rust-num/num-traits#152]
`Float` trait should require `copysign` function introduced in Rust 1.35: [f32::copysign](https://doc.rust-lang.org/std/primitive.f32.html#method.copysign), [f64::copysign](https://doc.rust-lang.org/std/primitive.f64.html#method.copysign)

**Comment by cuviper** [comment]
We can add it as long as there's a default implementation, but I think that should be possible. Using the `std` method should also be conditional on compiler support.

**Comment by cuviper** [comment]
When `libm` is enabled, we can also use its `copysign`/`copysignf` for older-`std` and `no_std` builds.
