### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by krtab** [rust-num/num-traits#166]
Hi !

This repo has both the Apache and MIT licenses, as most of the main rust repo, but is lacking a copyright notice indicating that any of the two can be chosen at the discretion of the user. Rust's main repo uses the following one: https://github.com/rust-lang/rust/blob/master/COPYRIGHT.

I am not a lawyer but I believe that without an explicit mention that the user is free to choose, the most restrictive license (which I guess is the Apache) applies.

Thanks a lot for your work

**Comment by cuviper** [comment]
The intention is to allow either for users, which also means contributions are under both licenses.

Would it satisfy you if we change `Cargo.toml`'s "MIT/Apache-2.0" to "MIT OR Apache-2.0"? But if we do need an explicit `COPYRIGHT` file, that's possible.

**Comment by krtab** [comment]
Thanks for your quick reply!

> Would it satisfy you if we change Cargo.toml's "MIT/Apache-2.0" to "MIT OR Apache-2.0"?

As of now I don't really have a need for licensing to be clarified: I was just thinking of copy-pasting some of your code in an MIT-licensed project but finally resorted to depend on the crate itself, so in a way I already am "satisfied". That being said, Cargo's [reference](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) mandates that the license field is a valid SPDX expression, and hence  `"MIT OR Apache-2.0"` would be better.

> But if we do need an explicit COPYRIGHT file, that's possible.

Once again, I am not really well-versed in copyright law, but my personal opinion would by that having a COPYRIGHT or LICENSE file clearly stating that the code is distributed under both licenses and that one may choose is the "cleanest" thing: it doesn't cost much and allows everyone to use your library to the extent you had in mind when dual-licensing it, even if they are for example employed by a company with strong legal requirements.
