### ISSUE TITLE
Misleading ToPrimitive / NumCast behavior to a float type with precision loss

### ISSUE THREAD

**Issue by Enet4** [rust-num/num-traits#175]
The documentation of the traits `ToPrimitive` and `NumCast` usually describe that it returns `None` when the source value cannot be represented in the target type.

([quote](https://docs.rs/num-traits/0.2.12/num_traits/cast/trait.NumCast.html#tymethod.from))

> Creates a number from another value that can be converted into a primitive via the ToPrimitive trait. If the source value cannot be represented by the target type, then None is returned.

However, in practice these methods will not return `None` when converting integer values which cannot be _fully_ represented (without precision loss) as a floating point type. As an example, `ToPrimitive` admits a conversion from `16_777_217_u32` to `f32`, losing one bit of precision in the process:

```
let x: u32 = 16_777_217;
let y = x.to_f32();
println!("{:?}", y);
```
```none
Some(16777216.0)
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f73687d2e63d97c4619f375e44083f76)

I am not entirely familiar with how the current implementation handles conversions to floating point types, but it feels that what is indicated as "can or cannot be represented" is worth clarifying in the documentation.

**Comment by cuviper** [comment]
Basically, the current implementation is only concerned with overflow, and loss of precision is accepted.

**Comment by cuviper** [comment]
Floats truncating to integers would be another loss of precision.

**Comment by Enet4** [comment]
I believe that these details are important. Shall I send a PR to expand the documentation, or are there plans to adjust the behaviour of these traits?

**Comment by cuviper** [comment]
I think it would be too surprising to change this behavior, so clarifying the documentation would be better. A PR is welcome, thanks!
