### ISSUE TITLE
Add a trait "IsSigned" or similar

### ISSUE THREAD

**Issue by Pardoxa** [rust-num/num-traits#187]
I think a trait like
```Rust
pub trait IsSigned{
   fn is_signed() -> bool;
}

// and other unsigned integer
impl IsSigned for usize {
    fn is_signed() -> bool {
        false
    }
}

// and other signed integer
impl IsSigned for isize {
   fn is_signed(){
       true
   }
}
```
would be a good addition. 

If there are optimizations, which only make sense for signed or unsigned types, this would enable 
us to use them.

**Comment by cuviper** [comment]
I'm not really keen on adding runtime methods for something that should be a type-system check, like `T: Signed`. In an ideal world where Rust specialization is finally available, you would be able to implement your algorithm optimizations based on those kind of type constraints. In the short term, you can always implement `IsSigned` yourself.

If you're only dealing with bounded integers, like the primitives, then `Bounded::min_value().is_zero()` is a decent indicator for an unsigned type.

**Comment by Pardoxa** [comment]
I believe the compiler would compile the runtime check out, since it knows that the result can only be true (or false).
But I get your point. 

And thanks for pointing out `Bounded::min_value().is_zero()` :)
