### ISSUE TITLE
Outdated unsoundness information in AsPrimitive documentation

### ISSUE THREAD

**Issue by kotauskas** [rust-num/num-traits#188]
The [page for `AsPrimitive`][`AsPrimitive`] mentions soundness holes from old versions of Rust related to floating point cast results, more specifically, [#10184] and [#15536]. Those have now been resolved, which is why the documentation should remove mentions of those bugs or explicitly state that those have been fixed and no longer cause undefined behavior.

[`AsPrimitive`]: https://docs.rs/num-traits/0.2.12/num_traits/cast/trait.AsPrimitive.html#safety " "
[#10184]: https://github.com/rust-lang/rust/issues/10184 " "
[#15536]: https://github.com/rust-lang/rust/issues/15536 " "

**Comment by cuviper** [comment]
#184 updated this, but it hasn't been published in a release yet.
