### ISSUE TITLE
Extract some kind of RealNumber trait out of Float and make Float require it

### ISSUE THREAD

**Issue by yoanlcq** [rust-num/num-traits#19]
Greetings,

This proposal isn't supposed to be a breaking change, but I suspect it would end up like one anyway.
I've searched for similar issues and the closest one I could find is Option 2 presented in [#321](https://github.com/rust-num/num/issues/321).

**The problem**  
I'm writing [yet-another generic vector/matrix math library](https://github.com/yoanlcq/vek).  
It also provides a `Lerp<Factor>` trait where `Factor` is expected to behave like a real number; And, as of today, everywhere I require a `T` to be a real number, I write `where T: Float`.  
Often, I find that my only use case is either to call trigonometric functions on `T`, or guarantee that `T` can represent numbers between 0 and 1.

Here's the thing: I would like my library to work with less common real number types such as fixed-point; And today, fixed-point numbers cannot meaningfully implement `Float`, because `infinity()`, `classify()` and some others make no sense for them, however I know they have trigonometric functions which is what I actually use `Float` for.  
Essentially, `Float` forcefully ties together two concepts that should be separate IMO: "something that behaves like a floating-point number", and "something that behaves like a real number, regardless of the underlying representation".

**The proposal**  
Extract floating-point-agnostic items of `Float` into a new `RealNum` trait (not sure about the name), and make `Float` require `RealNum`.

```rust
pub trait Float: RealNum {
    fn nan() -> Self;
    fn infinity() -> Self;
    fn neg_infinity() -> Self;
    fn neg_zero() -> Self; // Not sure about this one. Does it belong to RealNum instead ?
    fn is_nan(self) -> bool;
    fn is_infinite(self) -> bool;
    fn is_finite(self) -> bool;
    fn is_normal(self) -> bool;
    fn classify(self) -> FpCategory;
    fn integer_decode(self) -> (u64, i16, i8);
}
pub trait RealNum: Num + Copy + NumCast + PartialOrd + Neg<Output = Self> {
    fn min_value() -> Self;
    fn min_positive_value() -> Self;
    fn max_value() -> Self;
    fn floor(self) -> Self;
    fn ceil(self) -> Self;
    fn round(self) -> Self;
    fn trunc(self) -> Self;
    fn fract(self) -> Self;
    fn abs(self) -> Self;
    fn signum(self) -> Self;
    fn is_sign_positive(self) -> bool;
    fn is_sign_negative(self) -> bool;
    fn mul_add(self, a: Self, b: Self) -> Self;
    fn recip(self) -> Self;
    fn powi(self, n: i32) -> Self;
    fn powf(self, n: Self) -> Self;
    fn sqrt(self) -> Self;
    fn exp(self) -> Self;
    fn exp2(self) -> Self;
    fn ln(self) -> Self;
    fn log(self, base: Self) -> Self;
    fn log2(self) -> Self;
    fn log10(self) -> Self;
    fn max(self, other: Self) -> Self;
    fn min(self, other: Self) -> Self;
    fn abs_sub(self, other: Self) -> Self;
    fn cbrt(self) -> Self;
    fn hypot(self, other: Self) -> Self;
    fn sin(self) -> Self;
    fn cos(self) -> Self;
    fn tan(self) -> Self;
    fn asin(self) -> Self;
    fn acos(self) -> Self;
    fn atan(self) -> Self;
    fn atan2(self, other: Self) -> Self;
    fn sin_cos(self) -> (Self, Self);
    fn exp_m1(self) -> Self;
    fn ln_1p(self) -> Self;
    fn sinh(self) -> Self;
    fn cosh(self) -> Self;
    fn tanh(self) -> Self;
    fn asinh(self) -> Self;
    fn acosh(self) -> Self;
    fn atanh(self) -> Self;
    fn epsilon() -> Self { ... }
    fn to_degrees(self) -> Self { ... }
    fn to_radians(self) -> Self { ... }
}
```

That's pretty much the idea, but I suspect this would break existing `impl Float for T` in the wild.  

An (uglier, IMO) alternative would be to duplicate appropriate `Float` items instead (into `RealNum`), then make an universal impl so that `T: Float` implements `RealNum`.

I'm pretty sure I haven't foreseen all problems. Thanks in advance for considering anyway! :)

**Comment by cuviper** [comment]
It's *definitely* a breaking change for external implementors, as you mention. The new trait would have to stand alone. But I'd guess that's not so bad since implementors wouldn't have to do both, just the one most appropriate to them.

**Comment by yoanlcq** [comment]
I figure that the plan could be to add that new `RealNum` trait without touching `Float`, by copy-pasting appropriate items, then adding `impl<T: Float> RealNum for T { /* trivial impls here */ }` so that `RealNum` is useful to everyone right away.  
Somewhere in there we'd leave a note saying "in the next major version increase, let's make Float require RealNum, and remove intersecting items." (or not - it's not mandatory)

I would be interested in doing a PR that does this, if you're OK with that. If not, it's fine too!  
For now, people that really need it can make their fixed-point types implement `Float`'s items, but use `unimplemented!{}` on those that are floating-point-specific - then, they only have to make sure these items are never used.  
Alternatively, they can implement these items "incorrectly" but in a way that doesn't panic.

**Comment by porky11** [comment]
So the problem is, that when splitting hierarchy, the implementors of Float will now additionaly have to implement RealNum, isn't it?
I don't think, anyone would implement Float, because it's only suited for floats like the built in types.
Maybe it's used for wrapper types.
Maybe it would be useful to be able to implement functions of supertraits in subtraits. This should then solve the current problem.
Is it worth thinking about an RFC for such a feature?

**Comment by cuviper** [comment]
> So the problem is, that when splitting hierarchy, the implementors of Float will now additionaly have to implement RealNum, isn't it?
> I don't think, anyone would implement Float, because it's only suited for floats like the built in types.
> Maybe it's used for wrapper types.

Exactly -- for example, one such wrapper that I know of is [`NoisyFloat`](https://docs.rs/noisy_float/0.1.4/noisy_float/struct.NoisyFloat.html#impl-Float).

> Maybe it would be useful to be able to implement functions of supertraits in subtraits. This should then solve the current problem.
> Is it worth thinking about an RFC for such a feature?

You mean as a new language feature?  I'm not sure if this is a frequent enough scenario to warrant that, but it doesn't hurt to propose the idea.  Maybe start as a pre-RFC on the internals forum.
