### ISSUE TITLE
Make the Float trait depend on FloatConst.

### ISSUE THREAD

**Issue by nical** [rust-num/num-traits#20]
In my (arguably limited) experience with using the num traits, `FloatConst` is most of the time used along with `Float`. It would simplify a lot of type signatures if the `Float` trait bound implied `FloatConst`.
I'll happily submit a PR if the idea is sound.

**Comment by cuviper** [comment]
It's a breaking change to extend a trait that way.

Ideally, we might not have made `FloatConst` separate at all, just adding those directly to `Float`, but we'd have to provide defaults for any new trait items too.

For your own crates, you could create a local meta-trait that requires the `Float + FloatConst` combination though.

**Comment by nical** [comment]
Yeah. That's just a paper cut and I totally understand if it isn't worth making a breaking change just for that. If there's any plan to do a breaking change for whatever other reason It would be great to take this occasion to consolidate more features into the Float trait.

**Comment by cuviper** [comment]
I'm considering a semver bump for #16, but only to tweak features, not any breaking API change.  But we can keep this issue for some future API cleanup.

**Comment by cuviper** [comment]
I've decided to limit the clutter of `breaking change` issues, so they will now be tracked collectively in #47.  I'm closing this issue for now as `postponed` but we can still discuss its merits here as needed.
