### ISSUE TITLE
Some way to combine Bounded and Unsigned + Zero

### ISSUE THREAD

**Issue by clarfonthey** [rust-num/num-traits#208]
Right now it would be a breaking change to split up the `Bounded` trait, but I at least have one use case for this after messing around with AltSysrq/proptest#235: there are types that are lower-bounded but not upper-bounded, specifically `BigUint`. Would be nice to be able to have a trait that lets you get a min_value without requiring a max_value, since right now `Bounded` and `Unsigned + Zero` may overlap and we can't rely on that.

**Comment by cuviper** [comment]
I'm surprised there's a scenario where a possibly-negative minimum would be useful without also caring about a maximum. Can you show an example of how you would use this?

Maybe we could have a trait that returns `Option<Self>` bounds? But I'm not sure if there's any type that would have an upper bound and not lower, so maybe a simple `LowerBounded` trait is enough.

**Comment by clarfonthey** [comment]
In this particular case, it was because `RangeTo` can be converted to a `Range` for unsigned integers and bounded integers, but `RangeFull` cannot.

**Comment by clarfonthey** [comment]
Closing this issue since the PR I merged accounts for this.
