### ISSUE TITLE
Why doesnt Num implement PartialOrd?

### ISSUE THREAD

**Issue by Vaxeral** [rust-num/num-traits#216]
I undertsand why Num cant implement Ord (because Num encompasses all numbers including floats which cannot implement Ord) but why doesnt it implement PartialOrd?  Im trying to make my own num-traits library for ahem "Learning purposes" and im learning quite a bit about traits and what it means for a number to be unsigned.

**Comment by Vaxeral** [comment]
Like numbers by thier very definition should be Ord or at least PartialOrd

**Comment by Vaxeral** [comment]
I do realize that i could just bound the type by PartialOrd or use PrimInt but im just curious as to why Unsigned doesnt implement PartialOrd.

**Comment by Vaxeral** [comment]
Ah ive found out something.  This will not work.
```rust
fn something<T: PrimInt>(x: T) {
    x > 1;
}
```
Is there anyway to make it work?

**Comment by Vaxeral** [comment]
ah but this does work
```rust
fn something<T: PrimInt + Into<u8>>(x: T) {
    x.into() > 1u8;
}
```
Sorry for all the comments i hope you can still answer my original question.

**Comment by Vaxeral** [comment]
ah but this does work
```rust
fn something<T: PrimInt + Into<u32>>(x: T) {
    x.into() > 1u32;
}

fn main() {
    println!("Hello, world!");
    something(1u8);
}
```

**Comment by cuviper** [comment]
> Like numbers by their very definition should be Ord or at least PartialOrd

Not all -- complex numbers for example are not ordered.

As for literals like `1`, unfortunately there's nothing in the type system that can directly help with making that generic. Less directly, you can use the `Zero` and `One` traits for those particular values, or any of the suite of conversions traits: the standard `From`/`Into` and `TryFrom`/`TryInto`, or this crate's `NumCast`, `FromPrimitive`, `ToPrimitive`, and `AsPrimitive`.

**Comment by Vaxeral** [comment]
Thanks for answering my questions.  I might not be able to make a num traits lib as good as yours but at least ive learned something.
