### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by jpochyla** [rust-num/num-traits#217]
Hi! I'm using the `proptest` crate, which has `num-traits` 0.2.14 in the dependency tree. I have `proptest` as a `dev-dependency`, my crate is `no-std`, but NOT in the test profile, I have `resolver = "2"` set, but anyway `num-traits` appear only once in my dep tree. Build of the test binary fails at `num-traits`, with the following linker errors. Any ideas, please?

<details>
<summary>Compile log</summary>
<pre>
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-arch" "x86_64" "-L" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/jpochyla/Projects/trezor/trezor-firmware/core/embed/rust/../../build/unix/rust/debug/build/num-traits-a683586a3053925e/build_script_build-a683586a3053925e.build_script_build.7pfw08vp-cgu.0.rcgu.o" "/Users/jpochyla/Projects/trezor/trezor-firmware/core/embed/rust/../../build/unix/rust/debug/build/num-traits-a683586a3053925e/build_script_build-a683586a3053925e.build_script_build.7pfw08vp-cgu.1.rcgu.o" "/Users/jpochyla/Projects/trezor/trezor-firmware/core/embed/rust/../../build/unix/rust/debug/build/num-traits-a683586a3053925e/build_script_build-a683586a3053925e.build_script_build.7pfw08vp-cgu.2.rcgu.o" "/Users/jpochyla/Projects/trezor/trezor-firmware/core/embed/rust/../../build/unix/rust/debug/build/num-traits-a683586a3053925e/build_script_build-a683586a3053925e.build_script_build.7pfw08vp-cgu.3.rcgu.o" "/Users/jpochyla/Projects/trezor/trezor-firmware/core/embed/rust/../../build/unix/rust/debug/build/num-traits-a683586a3053925e/build_script_build-a683586a3053925e.build_script_build.7pfw08vp-cgu.4.rcgu.o" "/Users/jpochyla/Projects/trezor/trezor-firmware/core/embed/rust/../../build/unix/rust/debug/build/num-traits-a683586a3053925e/build_script_build-a683586a3053925e.build_script_build.7pfw08vp-cgu.5.rcgu.o" "/Users/jpochyla/Projects/trezor/trezor-firmware/core/embed/rust/../../build/unix/rust/debug/build/num-traits-a683586a3053925e/build_script_build-a683586a3053925e.build_script_build.7pfw08vp-cgu.6.rcgu.o" "/Users/jpochyla/Projects/trezor/trezor-firmware/core/embed/rust/../../build/unix/rust/debug/build/num-traits-a683586a3053925e/build_script_build-a683586a3053925e.build_script_build.7pfw08vp-cgu.7.rcgu.o" "-o" "/Users/jpochyla/Projects/trezor/trezor-firmware/core/embed/rust/../../build/unix/rust/debug/build/num-traits-a683586a3053925e/build_script_build-a683586a3053925e" "/Users/jpochyla/Projects/trezor/trezor-firmware/core/embed/rust/../../build/unix/rust/debug/build/num-traits-a683586a3053925e/build_script_build-a683586a3053925e.1hb5netzni4tpjun.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/jpochyla/Projects/trezor/trezor-firmware/core/embed/rust/../../build/unix/rust/debug/deps" "-L" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/jpochyla/Projects/trezor/trezor-firmware/core/build/unix/rust/debug/deps/libautocfg-31df4f8e3bb7ec7c.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-9225b8e469c32698.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-2fe2b8cd4fa63c34.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libobject-80083cf4ee7ee3ff.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-ddf3832e718029e6.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgimli-ba92c986e8ef2ca8.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-acd0bd456d8da820.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-55608c4156e4ecbb.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-4be618026614fdc7.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-fee25922260aa100.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-38ba3c5cc408e14d.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-899852a009fbe35f.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-5687564a0ccea916.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-9ed2c58b16cff4ee.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-244bf5611f93ff45.rlib" "/Users/jpochyla/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-70df686e6b4ebf5b.rlib" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv"
  = note: Undefined symbols for architecture x86_64:
            "core::ptr::unique::Unique$LT$T$GT$::as_ptr::h10cdee2202a14673", referenced from:
                alloc::raw_vec::RawVec$LT$T$C$A$GT$::ptr::h45fc92ddcad3fd9d in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.1.rcgu.o)
            "core::ptr::unique::Unique$LT$T$GT$::as_ptr::h6c1eb9a395a6cd00", referenced from:
                alloc::raw_vec::RawVec$LT$T$C$A$GT$::ptr::h02c8b442b17b496f in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.1.rcgu.o)
            "core::ptr::unique::Unique$LT$T$GT$::dangling::h292718da46282c4a", referenced from:
                alloc::raw_vec::RawVec$LT$T$C$A$GT$::new_in::hb8e7244e4fdf5735 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.1.rcgu.o)
            "core::ptr::drop_in_place$LT$autocfg..dir_contains_target..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$::h52bcdd001adbe216", referenced from:
                core::option::Option$LT$T$GT$::and_then::h44848b9e068ff2c1 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.8.rcgu.o)
            "core::ptr::drop_in_place$LT$core..alloc..layout..LayoutError$GT$::h8552db384a72736f", referenced from:
                l___unnamed_3 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.4.rcgu.o)
            "core::ptr::drop_in_place$LT$autocfg..error..Error$GT$::hfe81f0edea15d2f0", referenced from:
                core::result::Result$LT$T$C$E$GT$::unwrap::h3817c94075bbe3de in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.4.rcgu.o)
                l___unnamed_2 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.4.rcgu.o)
            "core::ptr::drop_in_place$LT$core..result..Result$LT$$LP$$RP$$C$std..io..error..Error$GT$$GT$::hafd0daa02d825f1a", referenced from:
                core::result::Result$LT$T$C$E$GT$::ok::hccf009ce3d4f5409 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.4.rcgu.o)
            "core::iter::adapters::map::Map$LT$I$C$F$GT$::new::h0a378b659af16735", referenced from:
                core::iter::traits::iterator::Iterator::map::h2bb3d9c6a8efdf8b in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.15.rcgu.o)
            "core::ptr::drop_in_place$LT$std..process..ChildStdin$GT$::h7ad6595f70cdba5a", referenced from:
                core::mem::drop::h6ea06fab5b65a5bf in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.2.rcgu.o)
                autocfg::AutoCfg::probe::h9da283b92a428321 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
                autocfg::AutoCfg::probe::hee5caa685b77f692 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
            "core::ops::function::FnOnce::call_once::hfa9a3ad849d09b2e", referenced from:
                core::cmp::max_by::h55cb839adee79a42 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.9.rcgu.o)
            "core::ops::function::FnOnce::call_once::haf6a90789b821485", referenced from:
                core::option::Option$LT$T$GT$::map::hb8ad942534ae05ee in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.8.rcgu.o)
            "core::iter::traits::iterator::Iterator::filter::hfa16e1c3bde58dea", referenced from:
                autocfg::AutoCfg::with_dir::_$u7b$$u7b$closure$u7d$$u7d$::h75771108921fe1bc in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
            "core::iter::traits::iterator::Iterator::collect::h75cff1f6e427095a", referenced from:
                autocfg::AutoCfg::with_dir::_$u7b$$u7b$closure$u7d$$u7d$::h75771108921fe1bc in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
            "core::ptr::drop_in_place$LT$alloc..string..String$GT$::h87cef7db7b314b06", referenced from:
                autocfg::AutoCfg::with_dir::_$u7b$$u7b$closure$u7d$$u7d$::h75771108921fe1bc in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
                autocfg::AutoCfg::probe::h9da283b92a428321 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
                std::process::Command::arg::hf6eeff90597603d1 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.9.rcgu.o)
            "core::iter::adapters::map::Map$LT$I$C$F$GT$::new::hb609321096c0fef5", referenced from:
                core::iter::traits::iterator::Iterator::map::h12626350f1ef1b1d in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.3.rcgu.o)
            "core::ptr::drop_in_place$LT$std..io..error..Error$GT$::h5e179e5fa5dd648d", referenced from:
                std::io::Write::write_all::h65355fa09e8e965f in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.9.rcgu.o)
            "core::ptr::drop_in_place$LT$autocfg..AutoCfg$GT$::h402c2532f7241ed7", referenced from:
                build_script_build::main::hbf213b2ab38b0c0c in build_script_build-a683586a3053925e.build_script_build.7pfw08vp-cgu.6.rcgu.o
                autocfg::AutoCfg::with_dir::hb358c2dab9a9c728 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
            "core::ptr::drop_in_place$LT$std..path..PathBuf$GT$::h1770c51497ad7ef3", referenced from:
                autocfg::AutoCfg::with_dir::hb358c2dab9a9c728 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
                autocfg::dir_contains_target::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hc9ce9196a6916100 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
            "core::ptr::drop_in_place$LT$alloc..vec..Vec$LT$u8$GT$$GT$::h4872a3b6fcc59e0f", referenced from:
                _$LT$T$u20$as$u20$alloc..slice..hack..ConvertVec$GT$::to_vec::h7f880103cc7a2cb2 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.7.rcgu.o)
            "core::ptr::drop_in_place$LT$$RF$autocfg..error..ErrorKind$GT$::ha9fdf6f2e52edd86", referenced from:
                l___unnamed_5 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.2.rcgu.o)
            "core::ptr::drop_in_place$LT$$RF$std..io..error..Error$GT$::hf91c5ce87f451e98", referenced from:
                l___unnamed_9 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.2.rcgu.o)
            "core::ptr::drop_in_place$LT$core..result..Result$LT$alloc..string..String$C$std..env..VarError$GT$$GT$::h41560c692fa530a1", referenced from:
                core::result::Result$LT$T$C$E$GT$::ok::h191aab4ad12a03d8 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.4.rcgu.o)
            "core::ptr::unique::Unique$LT$T$GT$::new_unchecked::h5c7481385022fd9e", referenced from:
                alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::h54c5cb914a16013d in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.1.rcgu.o)
            "core::ops::function::FnOnce::call_once::h19d5536461168c8c", referenced from:
                core::result::Result$LT$T$C$E$GT$::map::hac4bb4fc6449471b in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.4.rcgu.o)
            "core::ptr::drop_in_place$LT$$RF$$RF$str$GT$::hdfd5fe8e56eaa3ff", referenced from:
                l___unnamed_6 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.2.rcgu.o)
            "core::ptr::drop_in_place$LT$std..process..Child$GT$::h1f21acaf61c518b4", referenced from:
                autocfg::AutoCfg::probe::h9da283b92a428321 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
                autocfg::AutoCfg::probe::hee5caa685b77f692 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
            "core::ops::function::FnOnce::call_once::h4714547291a4184d", referenced from:
                core::result::Result$LT$T$C$E$GT$::map_err::hafec1711e2f76228 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.4.rcgu.o)
                core::result::Result$LT$T$C$E$GT$::map_err::hc509e1a920eb5c7c in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.4.rcgu.o)
                core::result::Result$LT$T$C$E$GT$::map_err::hc9cc4d92f3be7931 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.4.rcgu.o)
                core::result::Result$LT$T$C$E$GT$::map_err::hfb326d9ae20b3ea0 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.4.rcgu.o)
            "core::ptr::drop_in_place$LT$$RF$core..num..error..ParseIntError$GT$::hf48989ea69216aa0", referenced from:
                l___unnamed_8 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.2.rcgu.o)
            "core::ptr::drop_in_place$LT$std..process..Command$GT$::h4d06acfb5e31e1aa", referenced from:
                autocfg::AutoCfg::probe::h9da283b92a428321 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
                autocfg::AutoCfg::probe::hee5caa685b77f692 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
            "core::ptr::drop_in_place$LT$$RF$core..str..error..Utf8Error$GT$::h0aa52f075d9c8c3b", referenced from:
                l___unnamed_7 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.2.rcgu.o)
            "core::ptr::drop_in_place$LT$std..ffi..os_str..OsString$GT$::h9a16a4ee12ac4ee5", referenced from:
                autocfg::AutoCfg::with_dir::hb358c2dab9a9c728 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
            "autocfg::version::Version::from_rustc::h4e742a1db1b91fe8", referenced from:
                autocfg::AutoCfg::with_dir::hb358c2dab9a9c728 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
            "core::ptr::drop_in_place$LT$std..error..$LT$impl$u20$core..convert..From$LT$alloc..string..String$GT$$u20$for$u20$alloc..boxed..Box$LT$dyn$u20$std..error..Error$u2b$core..marker..Sync$u2b$core..marker..Send$GT$$GT$..from..StringError$GT$::h31bfbb23e217021c", referenced from:
                l___unnamed_1 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.2.rcgu.o)
            "core::ptr::drop_in_place$LT$autocfg..dir_contains_target..$u7b$$u7b$closure$u7d$$u7d$$GT$::h88f32a59c422a1e2", referenced from:
                core::option::Option$LT$T$GT$::and_then::h55e49168fa48efdc in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.8.rcgu.o)
            "core::ptr::drop_in_place$LT$core..option..Option$LT$std..process..ChildStdin$GT$$GT$::h559b3180e6b8fcdd", referenced from:
                core::mem::replace::hb639483a9df0fb73 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.2.rcgu.o)
            "core::ptr::drop_in_place$LT$core..result..Result$LT$bool$C$autocfg..error..Error$GT$$GT$::ha943ab4b6d4f2386", referenced from:
                core::result::Result$LT$T$C$E$GT$::unwrap_or::h74732362fd45b5ab in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.4.rcgu.o)
            "core::ptr::drop_in_place$LT$core..option..Option$LT$std..ffi..os_str..OsString$GT$$GT$::hce796a433e317942", referenced from:
                build_script_build::main::hbf213b2ab38b0c0c in build_script_build-a683586a3053925e.build_script_build.7pfw08vp-cgu.6.rcgu.o
                autocfg::AutoCfg::with_dir::hb358c2dab9a9c728 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
                autocfg::dir_contains_target::he8332bac895a8926 in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
                autocfg::dir_contains_target::_$u7b$$u7b$closure$u7d$$u7d$::h23fc5ee81cdfdfbf in libautocfg-31df4f8e3bb7ec7c.rlib(autocfg-31df4f8e3bb7ec7c.autocfg.4bb35qx4-cgu.11.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: could not compile `num-traits`
</pre>
</details>

**Comment by cuviper** [comment]
The error appears to be while linking `num-traits`' own build script. But neither `num-traits` nor its dependency `autocfg` do any tricks with linking libraries or anything, so I guess there's something going wrong with the toolchain, either `rustc` or `cargo`.

**Comment by jpochyla** [comment]
Thanks for the reply, it seems to work using nightly (I was testing with the latest stable before). So, hopefully an already fixed bug in rustc or cargo. Closing!
