### ISSUE TITLE
Non-primitive integer trait

### ISSUE THREAD

**Issue by CraftSpider** [rust-num/num-traits#219]
It would be nice to have a trait that represents any integer, not just copyable or primitive ones. That way one could also abstract over, say, a BigInt type, or any similar thing.

**Comment by cuviper** [comment]
The `num-integer` crate has `Integer`.

**Comment by CraftSpider** [comment]
Thanks, that's what I'm looking for. Though kind of sad it's spread into another crate, it feels like it would fit nicely alongside `Real` in this one. But I understand if that's considered not really in-scope.
