### ISSUE TITLE
Relationship `Real` and `Float`

### ISSUE THREAD

**Issue by fabianboesiger** [rust-num/num-traits#222]
The following code:

```rust
use num_traits::{Zero, real::Real};
use ordered_float::NotNan;

struct X<R: Real>(R);

fn main() {
    X(NotNan::zero());
}
```

Results in the compile-time error:

```
error[E0277]: the trait bound `NotNan<_>: Float` is not satisfied
 --> src/main.rs:7:7
  |
7 |     X(NotNan::zero());
  |       ^^^^^^^^^^^^^^ the trait `Float` is not implemented for `NotNan<_>`
  |
  = note: required because of the requirements on the impl of `Real` for `NotNan<_>`
note: required by `X`
```

This confuses me a bit. Why should `NotNan<_>: Float` be satisfied, if the requirements are impl `Real`?

Also I'm aware that `NotNan` currently doesn't implement `Real`, but that shouldn't be the reason for this error. Thanks for any feedback!

**Comment by cuviper** [comment]
There is a blanket `impl<T: Float> Real for T`, so I think if you don't independently implement `Real`, the compiler will assume this `impl` should apply, and then it complains about the transitive `T: Float` constraint.

**Comment by fabianboesiger** [comment]
Thank you so much! Implementing `Real` for `NotNan` fixes the issue. I didn't realize that the compiler assumes `impl<T: Float> Real for T` should apply.
