### ISSUE TITLE
leading_ones and trailing_ones missing for PrimInt

### ISSUE THREAD

**Issue by StephanvanSchaik** [rust-num/num-traits#223]
It seems like the `leading_ones()` and `trailing_ones()` functions are missing for the `PrimInt` trait. However, I am not entirely sure why as the `leading_zeros()` and `trailing_zeros()` seem to be available.

While I could invert the bit representation and use the `trailing_zeros()` function for now, it would be convenient if I could just use the `trailing_ones()` function instead.

**Comment by cuviper** [comment]
I finally published that a couple days ago in 0.2.15.
