### ISSUE TITLE
Does not compiles with target-feature=-sse2

### ISSUE THREAD

**Issue by tower120** [rust-num/num-traits#261]
When I trying to compile `num-traits` with 
```
[build]
rustflags = ["-Ctarget-feature=-sse2"] 
```
I get:

```
   Compiling num-traits v0.2.15
error: src\lib.rs:386:0: in function _ZN39_$LT$f64$u20$as$u20$num_traits..Num$GT$14from_str_radix17h59b1ae50b18378abE void (ptr, ptr, i64, i32): SSE2 register return with SSE2 disable
```

**Comment by CryZe** [comment]
You can't turn off sse2 like that because std is pre-compiled with sse2.

**Comment by tower120** [comment]
That's not that I'm trying to disable sse2 specifically for `num-traits`....

So, sse2 required for `num-traits`? Does that means it can't be used with arm/mac?
If so - that should be mentioned somewhere in the docs.

**Comment by tower120** [comment]
> You can't turn off sse2 like that because std is pre-compiled with sse2

Oh I lost **std** word, first time I read that.

https://docs.rs/safe_arch/latest/safe_arch/#compile-time-cpu-target-features

Now I see that.
