### ISSUE TITLE
Add minimal permissions to GitHub workflows

### ISSUE THREAD

**Issue by pnacht** [rust-num/num-traits#262]
GitHub workflows run with write-all permissions. This makes repositories vulnerable to supply-chain attacks.

Given num-traits' workflows are mainly for testing, they don't require such broad permissions. I'd therefore like to help the project close this vulnerability.

This can be done in two ways:
1. We can add top-level read-only permissions to all the workflows; and/or
2. You can change the repository settings to change the default permissions from write-all to read-only.

I'll send a PR along with this issue setting the top-level permissions on the workflows.

Or, if you'd rather (or also wish to) change the repository's default settings:

1. Open the repo settings
2. Go to [Actions > General](https://github.com/rust-num/num-traits/settings/actions)
3. Under "Workflow permissions", set them to "Read repository contents and packages permissions"

---

**Disclosure:** My name is Pedro and I work with Google and the [Open Source Security Foundation (OpenSSF)](https://www.openssf.org) to improve the supply-chain security of the open-source ecosystem.

**Comment by cuviper** [comment]
> Or, if you'd rather (or also wish to) change the repository's default settings:

I have changed this at the org level, and confirmed that it propagated to all repo settings.

But this is not visible to anyone outside, is it? So how did you know... Are you filing these issues with the assumption that folks have left read/write enabled?

**Comment by pnacht** [comment]
It isn't transparent to outsiders, no, but it can be sniffed out! Just need to look at the workflow logs, in the "Set up job" step there's a "GITHUB_TOKEN permissions" section which lists all permissions granted to that particular job ([example](https://github.com/rust-num/num-traits/actions/runs/4395045495/jobs/7696531304)].

Though, if I'm being honest, I could just as easily assume people left things as write-all... exceptions are rare!

**Comment by pnacht** [comment]
The value is mainly in redundancy (in case someone gets confused and changes the setting) and config-as-code, which makes it easier for users to see your workflows are secure. So the absolute best practice would be to do both, but just changing the setting already gets you 99% of the way there, so totally understandable if you'd rather skip the explicit permissions.

**Comment by pnacht** [comment]
Also, some tools (for example, the [OpenSSF Scorecard](https://github.com/ossf/scorecard)) score projects' supply-chain security posture, and they check this sort of thing. For token permissions, they scan for explicit permissions since hunting through logs is too convoluted.

**Comment by pnacht** [comment]
Closing this since the repo default was already changed!
