### ISSUE TITLE
Check if `PrimInt` is even or not

### ISSUE THREAD

**Issue by matthew-hennefarth** [rust-num/num-traits#273]
Is there any neat way to check if a primitive integer is even or odd? Currently I would imagine either some casts or some bit-wise manipulations on the generic type PrimInt is needed and it would obfuscate code readibility. For example, if we used the modulo way:

```rust
fn some_func<T>(n: T) -> bool
where 
    T: PrimInt + FromPrimitive,
{
    // Do something else...
    n % T::from_usize(2).unwrap() == T::zero()
}
```

versus something like

```rust
fn some_func<T>(n: T) -> bool
where 
    T: PrimInt + FromPrimitive,
{
    // Do something else...
    n.is_even()
}
```

Thoughts? I could work on a PR if this would be appreciated.

**Comment by cuviper** [comment]
Those methods to exist more generally on `Integer`, so I'd be wary of adding ambiguity if `PrimInt` got the same.
https://docs.rs/num-integer/latest/num_integer/trait.Integer.html#tymethod.is_even

To do it yourself, `PrimInt` includes `Shl`/`Shr<usize>`, so you can use `((x >> 1) << 1) == x` for even.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=02fcdb7c587a5a6b86c74400e7b476d4

**Comment by matthew-hennefarth** [comment]
Thanks! Makes sense to not have it in both `Integer` and `PrimInt` since it can cause conflicts.

**Comment by cuviper** [comment]
Another option is `n.trailing_zeros() > 0`. On x86_64, it's optimized to the same bit test either way.
