### ISSUE TITLE
Should `num::{ToPrimitive,FromPrimitive}` be implemented in terms of `std::convert::{Into,TryFrom}`?

### ISSUE THREAD

**Issue by dbarella** [rust-num/num-traits#29]
[std::convert](https://doc.rust-lang.org/std/convert/index.html) supplies `Into` and `TryFrom` traits which seem applicable to the existing `num::ToPrimitive` and `num::FromPrimitive` traits.

In theory, the `std::convert` traits are the more future-proof way to implement all of this. That said, I stared at `cast.rs` for a while trying to figure out a good way to make this change, and I haven't got anything useful so far -- the problem is that `num` reprovides `ToPrimitive` and `FromPrimitive` to the world, which means that they can't be removed without breaking current users (at least, as far as I can tell).

**Comment by cuviper** [comment]
I'm not really sure what you're suggesting.

Sure, people should prefer `From`/`Into` for infallible conversions, and in the future should prefer `TryFrom`/`TryInto` for fallible conversions, but the latter are currently unstable traits.  When they are stable, then I guess `FromPrimitive` and `ToPrimitive` will be obsolete, but that's not really a problem, is it?

**Comment by cuviper** [comment]
So, I think the answer to the original question is "no".  Feel free to reopen this if you want more discussion.
