### ISSUE TITLE
Add `BitOrAssign` etc. to `PrimInt`

### ISSUE THREAD

**Issue by Enyium** [rust-num/num-traits#304]
`PrimInt` already has bounds for `BitOr` etc. Is it an oversight that the `...Assign` variants are missing?

Currently, I can do:

```
container = container | t;
```

...but not:

```
container |= t;
```

...when `t` has a `PrimInt` bound and `container` is initialized with `T::zero()`.

**Comment by cuviper** [comment]
I think it's because `Primint` is simply older -- all of the `OpAssign` traits were "only" stabilized in Rust 1.8.0, and it's a breaking change to add more requirements to `PrimInt` since it's not a sealed trait. But you could make your own extended trait that requires more, something like:

```rust
trait MyPrimInt: PrimInt + BitOrAssign + ... {}
impl<T: PrimInt + BitOrAssign + ...> MyPrimInt for T {}
```

**Comment by Enyium** [comment]
Don't you gather breaking changes to perform them one day?

**Comment by cuviper** [comment]
In theory, yes, but in practice I'm afraid that a breaking semver bump will fracture the ecosystem, since these traits are often used in others' public APIs.

**Comment by Enyium** [comment]
Hm, I guess I'll close this then.
