### ISSUE TITLE
Support for `const fn` for `ToPrimitive`?

### ISSUE THREAD

**Issue by tyrone-wu** [rust-num/num-traits#341]
Hello 👋. awesome crate!

I was wondering if it would be possible have another set of functions implemented from `ToPrimitve` be marked as `const fn` to directly return the primitive?

Thank you. 😸

**Comment by tyrone-wu** [comment]
Ah 😓, it looks like `const fn` in traits isn't allowed. However, it looks like there's some progress towards this!
https://github.com/rust-lang/rust/pull/131985

**Comment by tetofonta** [comment]
What about implementing the const method inside a dedicated impl for the enum and then referencing it inside the trait? This could be done in the `num-derive` crate following the following example (for FromPrimitive and IntoPrimitive):

``` rust
impl MyEnum {
    const fn new_from_primitive(value: u8){
        // from_primitive implementation
    }


    const fn into_primitive(self){
        // into implementation
    }
}

impl From<MuEnum> for u8 {
    fn from(enum_value: MyEnum) -> Self {
        enum_value.into_primitive()
    }
}

impl FromPrimitive for MyEnum {
    fn from_primitive(value: u8) -> Self {
        Self::new_from_primitive(value)
    }
}
```
