### ISSUE TITLE
FromPrimitive f64 trait casts to i64?

### ISSUE THREAD

**Issue by ambaxter** [rust-num/num-traits#35]
https://github.com/rust-num/num-traits/blob/bfd62d4638392deff20907ad078d2b1521aa45ba/src/cast.rs#L355

also 
https://github.com/rust-num/num-traits/blob/bfd62d4638392deff20907ad078d2b1521aa45ba/src/cast.rs#L75

Is this right?

**Comment by cuviper** [comment]
Those are the *default* implementations -- specific implementations should override that to work with floats directly, if they can do something better.

However, the first should probably be more like `i64::from_f64(n).and_then(Self::from_i64)` so it can handle overflow correctly -- at least when #12 is fixed.
