### ISSUE TITLE
Idea: Pow trait

### ISSUE THREAD

**Issue by clarcharr** [rust-num/num-traits#38]
I've been working on a crate which works with runtime-level units, and I think that having a generic `Pow` trait would be useful.

Essentially, it would be very similar to the other unary op traits, namely:

```
pub trait Pow<RHS> {
    type Output;
    fn pow(self, rhs: RHS) -> Self::Output;
}
```

And in most cases, this would simply do exponentiation by squaring as included in the existing `pow` functions. However, it may be easier to implement for some types, namely a unit could simply multiply a field that indicates what power of the given unit you have. Another example is that a type which constrains which values it has, e.g. a matrix which specifically performs scaling operations, could be modified to do less work.

This would be weird to implement and may cause confusion with the existing `pow` function, which is why I haven't offered a PR for it. But it might be nice to have in this crate.

**Comment by cuviper** [comment]
It makes sense to me, especially since types can make _internal_ decisions about stuff like #18.

**Comment by cuviper** [comment]
(We can de-emphasize the generic `fn pow()` in favor of this.)

**Comment by cuviper** [comment]
It might also be interesting that floats can implement both `Pow<Self>` and `Pow<i32>` using `powf` and `powi`, though only with `std` enabled.  All of the integers can forward to their inherent `pow` methods too, instead of using our own.

**Comment by termoshtt** [comment]
Looks good :) I think it is very useful since it can be implemented for `num_complex::Complex<T>`.
