### ISSUE TITLE
`saturating_mul` missing

### ISSUE THREAD

**Issue by ticky** [rust-num/num-traits#40]
Is the lack of `saturating_mul` in `num::Saturating` on purpose, or a mistake, or should it live somewhere else?

**Comment by cuviper** [comment]
It's historical -- that method was not added in `std` until rust 1.7.  And while our minimum rust is now beyond that, it would still be a breaking change for us to add this to `Saturating`.  We could break out separate traits per-op though, like the wrapping ops do -- `SaturatingMul` etc.

**Comment by cuviper** [comment]
Sure!

I guess it should take references, for consistency with the existing `WrappingOp` and `CheckedOp` traits, although that won't be consistent with `Saturating`.  Design is hard, legacy code is messy...
