### ISSUE TITLE
Add Default, Display, and Debug trait bounds to PrimInt

### ISSUE THREAD

**Issue by jturner314** [rust-num/num-traits#44]
The following trait bounds would be useful to add to `PrimInt` on the next breaking release:

* `Default`
* `Display`
* `Debug`

See also #36 and #43. This is a tracking issue for adding these trait bounds.

**Comment by cuviper** [comment]
I've decided to limit the clutter of `breaking change` issues, so they will now be tracked collectively in #47.  I'm closing this issue for now as `postponed` but we can still discuss its merits here as needed.
