### ISSUE TITLE
Easy conversions between `Signed` and `Unsigned`

### ISSUE THREAD

**Issue by clarcharr** [rust-num/num-traits#46]
It would be nice if `Signed` and `Unsigned` had a way to convert between each other, presumably via:

* `Signed::abs_unsigned`, which would losslessly convert the signed version to an unsigned version of the same size (`wrapping_abs` + `as` for primitives, and just extracting the inner `BigUint` for `BigInt`)
* `Unsigned::try_signed`, which would allow casting to the signed version if available.
* `Signed::Unsigned` and `Unsigned::Signed`, two associated types that would do the job.

This would be a breaking change but a useful one. For example, a `Pow` implementation for `Ratio` could leverage these methods so that the signed and unsigned versions relied on each others' implementations, instead of duplicating code.

**Comment by cuviper** [comment]
I've decided to limit the clutter of `breaking change` issues, so they will now be tracked collectively in #47.  I'm closing this issue for now as `postponed` but we can still discuss its merits here as needed.
