### ISSUE TITLE
Add method `is_one` to `One` trait

### ISSUE THREAD

**Issue by cuviper** [rust-num/num-traits#5]
_From @pyfisch on August 5, 2016 17:15_

The [`Zero` trait](http://rust-num.github.io/num/num/trait.Zero.html) contains two methods: `zero` returns the number 0 for the given type and `is_zero` is provided and can be used to check if a number is 0.

The [`One` trait](http://rust-num.github.io/num/num/trait.One.html) is similar but contains only the method `one` to create the number 1. Please also add a method to check if a number is one.

_Copied from original issue: rust-num/num#214_

**Comment by cuviper** [comment]
It turned out not so easy without a breaking change, although we could add it `where Self: PartialEq` for now to allow a default implementation, and drop that in a breaking change (eventually).

**Comment by cuviper** [comment]
That was rust-num/num#336 on the `next` branch.

**Comment by clarcharr** [comment]
The issue description/title should be updated to mention removing the `PartialEq` bound rather than adding the function.

**Comment by vks** [comment]
Shouldn't this be closed?

**Comment by cuviper** [comment]
I added the `PartialEq` note to #47 for breaking changes.
