### ISSUE TITLE
Idea: Log Trait

### ISSUE THREAD

**Issue by shingtaklam1324** [rust-num/num-traits#50]
With #38 's suggestion about a `Pow` trait, it would be useful to add the inverse of exponentiation as a trait. The proposed syntax is similar to the one for `Pow`

```rust
pub trait Log<RHS> {
    type Output;
    fn log(self, rhs: RHS) -> Self::Output;
}
```

This would most likely be necessary for `impl Pow<Complex<T>> for Complex<T>`.

Relevent issue on `num-complex`

rust-num/num-complex#18

**Comment by clarcharr** [comment]
I think that exponentiation is a good case because many types support it, whereas I can't find any useful case for logarithms outside floats and complex numbers, and extensions thereof.

Also, 99% of the time you'd be doing `ln(self) / ln(RHS)` so I don't see why the RHS is entirely necessary.
