### ISSUE TITLE
Use the libm crate for a full Float on no_std

### ISSUE THREAD

**Issue by cuviper** [rust-num/num-traits#75]
Currently, `num_traits::Float` is only available with `std`, and `no_std` only has the more limited `FloatCore` without all of transcendental functions like `sqrt`, `sin`, etc.  The new `libm` crate might be the way out of this, as an optional dependency to get `Float` on `no_std` too!

There's also `Real` and the signed and floating-point `Pow` (mapping to `powi` and `powf`) which all require `std` now, and should be feasible with `libm`.  I'm not sure about `MulAdd` and `MulAddAssign` though.

**Comment by vks** [comment]
`libm` is not ready yet, it panics with overflows in debug mode.

**Comment by cuviper** [comment]
Sure, we can hold off until it's more ready -- I'm not in any rush.  It could still be useful to do early exploration though, to identify any other shortcomings that `libm` might want to address.

**Comment by malobre** [comment]
Since #99 was merged shouldn't this be closed ?

**Comment by korken89** [comment]
Hi, please make a release including #99 this is a key component for a library I'm writing and I would love to have this!

CC @cuviper

**Comment by cuviper** [comment]
I will try to get to it this week.

**Comment by CryZe** [comment]
What's the status of this? It's been two weeks (sorry for maybe pinging this early, but this is my last blocker).

**Comment by korken89** [comment]
Same here, this is the only thing that is missing for me as well

**Comment by cuviper** [comment]
Sorry for the delay -- num-traits 0.2.9 is now published!
