### ISSUE TITLE
Feature Request: Add "Maximum" and "Minimum" traits (or a combined `MiniMax` trait)

### ISSUE THREAD

**Issue by phayes** [rust-num/num-traits#93]
Often times, it is useful to know the maximum and minimum values allowed by a numeric type. 

I'm hoping we could see a fairly simple trait that looks someting like this:

```rust
pub trait MiniMax {
    fn maximum() -> Self;
    fn minimum() -> Self;
}
```

Some examples:
  1. `u32.maximum()` would return `std::u32::MAX`
  2. `u32.minimum()` would return `0`
  3. `f64.maximum()` would return `std::f64::INFINITY`
  4. `f64.minimum()` would return `std::f64::NEG_INFINITY`

Unbounded finite types like BigInt simply wouldn't implement this trait.

**Comment by cuviper** [comment]
That would be [`Bounded`](https://docs.rs/num-traits/0.2.6/num_traits/bounds/trait.Bounded.html), although for floats it returns the min/max *finite* values.

**Comment by phayes** [comment]
Silly me, there it is. Apologies for the noise on the issue queue.   Closing this.
