### ISSUE TITLE
Zero not implemented for references

### ISSUE THREAD

**Issue by LukeMathWalker** [rust-num/num-traits#94]
Morning!
I was using the `Zero` trait and I realized it is not implemented for references (e.g. `&f64`).
Is there a specific reason behind this choice?

**Comment by cuviper** [comment]
`Zero::zero()` returns `Self`, so returning a reference would require some `static` storage.  I guess that's easy enough for primitives, and could be done with `lazy_static!` for things like `BigInt`.

But... what's the context?  Why do you want a trait that would give you a *reference* to a 0 value?

**Comment by LukeMathWalker** [comment]
I am writing a generic function that should be able to reduce (e.g. sum) both collections of numbers or collections of references to those numbers.

No issue with using Add as a bound - std implements it both for primitives and references to primitives - but it breaks for Zero.
On 4 Dec 2018, at 00:47, Josh Stone <notifications@github.com<mailto:notifications@github.com>> wrote:

Zero::zero() returns Self, so returning a reference would require some static storage. I guess that's easy enough for primitives, and could be done with lazy_static! for things like BigInt.

But... what's the context? Why do you want a trait that would give you a reference to a 0 value?

**Comment by cuviper** [comment]
> I am writing a generic function that should be able to reduce (e.g. sum) both collections of numbers or collections of references to those numbers.

Are you aware of the [`Sum`](https://doc.rust-lang.org/stable/std/iter/trait.Sum.html) trait?  I expect that's what you should be using.

> No issue with using Add as a bound - std implements it both for primitives and references to primitives - but it breaks for Zero.

`Add` on references still outputs values though.  I expect the same is true for your generic function -- even if you accept reference input, your accumulator and final output should be values.

Also note the supertrait here: `trait Zero: Sized + Add<Self, Output = Self>`.  That `Output` means you would need addition that creates references, which isn't really feasible.  So I think we actually **can't** implement `Zero` for things like `&f64` at all.

**Comment by cuviper** [comment]
> So I think we actually **can't** implement `Zero` for things like `&f64` at all.

Given this, I'm closing the issue. If you have further questions, I'm happy to help.
